import dotenv from 'dotenv';
dotenv.config();

import { evaluatePromptSafety } from './PromptFilter';
import { evaluateRiskGuardrails, TradeRequest } from './RiskGuardrail';
import { executeApprovedTrade, TradeProposal } from '../utils/agent';

export interface ExecutionReport {
  success: boolean;
  promptSafety: 'SAFE' | 'UNSAFE';
  riskGuardrail: 'PASSED' | 'BLOCKED';
  reentrancyGuard: 'PASSED' | 'BLOCKED';
  replayGuard: 'PASSED' | 'BLOCKED';
  message: string;
  orderId?: string;
}

// Stateful In-Memory Protection Registries for developers (Track 2 Focus)
const PROCESSED_SIGNATURES = new Set<string>();
let isExecuting = false;

export class AsiwajuAgentShield {
  /**
   * Orchestrates the complete defensive pipeline: Prompt Safety -> Risk Guardrails -> Re-entrancy -> Replay Protection -> Secure Execution
   * @param prompt The natural language user command or agent intent
   * @param tradeRequest The parsed structured trade parameters
   * @param transactionSignature A unique cryptographic nonce/signature generated by the client to prevent replays
   */
  public static async processSecureTrade(
    prompt: string,
    tradeRequest: TradeRequest,
    transactionSignature?: string
  ): Promise<ExecutionReport> {
    console.log(`🔒 [ShieldSDK] Intercepting transaction request for ${tradeRequest.symbol}...`);

    // 1. Stateful Re-entrancy Guard (Blocks race-conditions and malicious smart contract callbacks)
    if (isExecuting) {
      console.warn("🚨 [ShieldSDK] Re-entrancy Attack Blocked: Concurrent transaction execution detected.");
      return {
        success: false,
        promptSafety: 'SAFE',
        riskGuardrail: 'BLOCKED',
        reentrancyGuard: 'BLOCKED',
        replayGuard: 'PASSED',
        message: 'Re-entrancy Guard Triggered: Concurrent transaction thread blocked.'
      };
    }

    // Lock Execution
    isExecuting = true;

    try {
      // 2. Cryptographic Replay Attack Guard (Blocks dual-spend or repetitive execution clones)
      if (transactionSignature) {
        if (PROCESSED_SIGNATURES.has(transactionSignature)) {
          console.warn("🚨 [ShieldSDK] Signature Replay Attack Blocked: Duplicate transaction payload detected.");
          isExecuting = false; // Unlock
          return {
            success: false,
            promptSafety: 'SAFE',
            riskGuardrail: 'BLOCKED',
            reentrancyGuard: 'PASSED',
            replayGuard: 'BLOCKED',
            message: 'Signature Replay Guard Triggered: Duplicate transaction signature blocked.'
          };
        }
        PROCESSED_SIGNATURES.add(transactionSignature);
      }

      // 3. Prompt Safety Evaluation (AI Defense)
      const safetyReport = await evaluatePromptSafety(prompt);
      if (safetyReport.status === 'UNSAFE') {
        console.warn(`🔴 [ShieldSDK] Layer 1 Violation: Malicious or anomalous prompt detected.`);
        isExecuting = false; // Unlock
        return {
          success: false,
          promptSafety: 'UNSAFE',
          riskGuardrail: 'BLOCKED',
          reentrancyGuard: 'PASSED',
          replayGuard: 'PASSED',
          message: `Blocked by AI Security Filter: ${safetyReport.reason}`
        };
      }

      // 4. Programmatic Risk Evaluation (Code-Level Defense)
      const guardrailReport = evaluateRiskGuardrails(tradeRequest);
      if (!guardrailReport.passed) {
        console.warn(`🔴 [ShieldSDK] Layer 2 Violation: Programmatic risk bounds exceeded.`);
        isExecuting = false; // Unlock
        return {
          success: false,
          promptSafety: 'SAFE',
          riskGuardrail: 'BLOCKED',
          reentrancyGuard: 'PASSED',
          replayGuard: 'PASSED',
          message: `Blocked by Code Guardrails: ${guardrailReport.violations.join('; ')}`
        };
      }

      // 5. Secure Signing & Execution on Bitget
      const proposal: TradeProposal = {
        symbol: tradeRequest.symbol,
        side: tradeRequest.side,
        price: tradeRequest.price.toString(),
        quantity: tradeRequest.quantity.toString(),
        stopLoss: (tradeRequest.side === 'buy' ? tradeRequest.price * 0.975 : tradeRequest.price * 1.025).toString(),
        takeProfit: (tradeRequest.side === 'buy' ? tradeRequest.price * 1.05 : tradeRequest.price * 0.95).toString(),
        reason: 'Authorized via Asiwaju Agent Shield SDK middleware.'
      };

      const executionResult = await executeApprovedTrade(proposal);
      const [status, details] = executionResult.split(':');

      isExecuting = false; // Unlock

      if (status === 'SUCCESS') {
        return {
          success: true,
          promptSafety: 'SAFE',
          riskGuardrail: 'PASSED',
          reentrancyGuard: 'PASSED',
          replayGuard: 'PASSED',
          message: 'Transaction successfully executed on Bitget Spot V2.',
          orderId: details
        };
      } else {
        return {
          success: false,
          promptSafety: 'SAFE',
          riskGuardrail: 'PASSED',
          reentrancyGuard: 'PASSED',
          replayGuard: 'PASSED',
          message: `Exchange rejection: ${details}`
        };
      }

    } catch (error: any) {
      isExecuting = false; // Unlock
      console.error(`❌ [ShieldSDK] Exception: ${error.message}`);
      return {
        success: false,
        promptSafety: 'SAFE',
        riskGuardrail: 'PASSED',
        reentrancyGuard: 'PASSED',
        replayGuard: 'PASSED',
        message: `Execution pipeline exception: ${error.message}`
      };
    }
  }
}